[project]
name = "aiengineer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Charles Azam", email = "azamcharles0@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aider-chat",
    "litellm>=1.68.1",
    "pyforge",
    "smolagents>=1.15.0",
    "aider-chat>=0.83",
]

[project.scripts]
aiengineer = "aiengineer:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.uv.sources]
pyforge = { path = "../pyforge", editable = true }
aider-chat = { path = "../aider", editable = true }
smolagents = { path = "../smolagents", editable = true }

